services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./themes/src/main/resources/theme/invent:/opt/keycloak/themes/invent
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
